<?php
declare(strict_types=1);
$c=require __DIR__.'/config.php'; session_name('usfur_session'); session_start();
try{$pdo=new PDO("mysql:host={$c['db']['host']};dbname={$c['db']['name']};charset=utf8mb4",$c['db']['user'],$c['db']['pass'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);}catch(Throwable $e){$pdo=null;}
function e($x){return htmlspecialchars((string)$x,ENT_QUOTES,'UTF-8');} function uid(){return sprintf('%04x%04x-%04x-%04x-%04x-%04x%04x%04x',random_int(0,65535),random_int(0,65535),random_int(0,65535),random_int(32768,49151),random_int(0,65535),random_int(0,65535),random_int(0,65535),random_int(0,65535));}
function user(){global $pdo;if(empty($_SESSION['uid'])||!$pdo)return null;$q=$pdo->prepare("SELECT u.*,COALESCE(ur.role,'student') role FROM users u LEFT JOIN user_roles ur ON ur.user_id=u.id WHERE u.id=? LIMIT 1");$q->execute([$_SESSION['uid']]);return $q->fetch()?:null;}
function head($title){global $c,$u;$u=user();echo '<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'.e($title).'</title><link rel="stylesheet" href="style.css"></head><body><header class="nav"><a class="brand" href="index.php"><img src="/src/assets/usfur-logo.jpg" alt="USFUR">USFUR</a><nav><a href="index.php">Accueil</a><a href="?route=services">Services</a><a href="?route=partners">Partenaires</a><a href="?route=courses">Formations</a>'.($u?'<a href="?route='.($u['role']==='student'?'student':'admin').'">Espace</a><a href="?route=logout">Déconnexion</a>':'<a href="?route=auth">Connexion</a>').'</nav></header><div class="wrap">';}
function foot(){global $c;echo '</div><footer class="footer"><div><b>USFUR Islamic Finance Training & Consulting</b><br>Formation & conseil en finance islamique dans la zone CEMAC.</div><div>+237 690 895 554<br>admin@usfurcm.com</div><div><a target="_blank" href="https://wa.me/'.$c['mtech']['whatsapp'].'?text='.rawurlencode($c['mtech']['message']).'">Developped by <b>MTECHsolutions</b> · WhatsApp</a></div></footer></body></html>';}
$r=$_GET['route']??'home'; $u=user();
if($r==='logout'){session_destroy();header('Location:index.php');exit;}
if($r==='auth'&&$_SERVER['REQUEST_METHOD']==='POST'&&$pdo){try{if($_POST['act']==='login'){$q=$pdo->prepare("SELECT * FROM users WHERE email=? AND is_active=1");$q->execute([strtolower(trim($_POST['email']))]);$x=$q->fetch();if(!$x||!password_verify($_POST['password'],$x['password_hash']))throw new Exception('Email ou mot de passe incorrect.');$_SESSION['uid']=$x['id'];header('Location:index.php?route=student');exit;}else{$id=uid();$q=$pdo->prepare("INSERT INTO users(id,email,password_hash,full_name) VALUES(?,?,?,?)");$q->execute([$id,strtolower(trim($_POST['email'])),password_hash($_POST['password'],PASSWORD_DEFAULT),trim($_POST['full_name'])]);$pdo->prepare("INSERT INTO user_roles(id,user_id,role) VALUES(?,?,?)")->execute([uid(),$id,'student']);$_SESSION['uid']=$id;header('Location:index.php?route=student');exit;}}catch(Throwable $e){$err=$e->getMessage();}}
if($r==='enroll'&&$u&&$_SERVER['REQUEST_METHOD']==='POST'){$pdo->prepare("INSERT IGNORE INTO enrollments(id,student_id,course_id) VALUES(?,?,?)")->execute([uid(),$u['id'],$_POST['course_id']]);header('Location:index.php?route=student');exit;}
if($r==='course_create'&&$u&&$u['role']==='admin'&&$_SERVER['REQUEST_METHOD']==='POST'){$pdo->prepare("INSERT INTO courses(id,title,description,module_number,duration_minutes,max_participants,status) VALUES(?,?,?,?,?,?,?)")->execute([uid(),trim($_POST['title']),trim($_POST['description']),intval($_POST['module_number']),intval($_POST['duration_minutes']),intval($_POST['max_participants']),$_POST['status']]);header('Location:index.php?route=admin');exit;}
head('USFUR');
if($r==='home'){echo '<section class="hero"><div><p class="muted">USFUR Islamic Finance Training & Consulting</p><h1>Formation d’excellence en Finance Islamique</h1><p>Développez vos compétences en finance islamique, gouvernance, produits, Charia, takaful et sukuk avec une plateforme pensée pour les professionnels de la zone CEMAC.</p><a class="btn" href="?route=courses">Découvrir les formations</a></div><img src="/src/assets/hero-bg.jpg" alt="USFUR"></section><h2>Nos domaines</h2><div class="grid">'.implode('',array_map(fn($x)=>'<div class="card"><h3>'.e($x[0]).'</h3><p>'.e($x[1]).'</p></div>',[['Finance & Charia','Fondamentaux et conformité.'],['Produits islamiques','Mourabaha, ijara, musharaka, mudaraba.'],['Gouvernance','Conformité, contrôle et risques.'],['Takaful & Sukuk','Structures et applications.']])).'</div>';}
elseif($r==='services'){echo '<h1>Services</h1><div class="grid">'.implode('',array_map(fn($x)=>'<div class="card"><h3>'.e($x[0]).'</h3><p>'.e($x[1]).'</p></div>',[['Formation professionnelle','Programmes structurés et certification.'],['Conseil','Accompagnement des institutions et organisations.'],['Conformité Charia','Cadres, processus et documentation.'],['Produits financiers','Analyse et structuration de solutions.'],['Gouvernance','Gouvernance et gestion des risques.'],['Accompagnement CEMAC','Solutions adaptées au contexte régional.']])).'</div>';}
elseif($r==='partners'){echo '<h1>Partenaires & institutions</h1><div class="grid">';foreach($pdo->query("SELECT * FROM institutions WHERE is_active=1 ORDER BY name") as $x)echo '<div class="card"><h3>'.e($x['name']).'</h3><p>'.e($x['type']).' · '.e($x['city']).'</p></div>';echo '</div>';}
elseif($r==='courses'){$rows=$pdo->query("SELECT * FROM courses WHERE status<>'draft' ORDER BY module_number")->fetchAll();echo '<h1>Formations</h1><div class="grid">';foreach($rows as $x)echo '<div class="card"><p class="muted">Module '.e($x['module_number']).'</p><h3>'.e($x['title']).'</h3><p>'.nl2br(e($x['description'])).'</p><p>'.e($x['duration_minutes']).' minutes</p>'.($u&&$u['role']==='student'?'<form method="post" action="?route=enroll"><input type="hidden" name="course_id" value="'.e($x['id']).'"><button class="btn">S’inscrire</button></form>':'').'</div>';echo '</div>';}
elseif($r==='auth'){echo '<form class="box" method="post"><h1>'.(($mode=$_GET['mode']??'login')==='signup'?'Inscription':'Connexion').'</h1>'.(!empty($err)?'<div class="flash">'.e($err).'</div>':'').($mode==='signup'?'<label>Nom complet</label><input name="full_name" required>':'').'<label>Email</label><input type="email" name="email" required><label>Mot de passe</label><input type="password" name="password" minlength="6" required><input type="hidden" name="act" value="'.($mode==='signup'?'signup':'login').'"><button class="btn">Valider</button></form><p><a href="?route=auth&mode='.($mode==='signup'?'login':'signup').'">'.($mode==='signup'?'Connexion':'Créer un compte').'</a></p>';}
elseif($r==='student'){if(!$u){header('Location:index.php?route=auth');exit;}if($u['role']!=='student'){header('Location:index.php?route=admin');exit;}$q=$pdo->prepare("SELECT e.*,c.title FROM enrollments e JOIN courses c ON c.id=e.course_id WHERE e.student_id=?");$q->execute([$u['id']]);echo '<h1>Bienvenue, '.e($u['full_name']).'</h1><div class="grid">';foreach($q as $x)echo '<div class="card"><h3>'.e($x['title']).'</h3><p>Progression '.e($x['progress']).'% · '.e($x['status']).'</p></div>';echo '</div>';}
elseif($r==='admin'){if(!$u||$u['role']!=='admin'){http_response_code(403);echo '<h1>Accès refusé</h1>';foot();exit;}echo '<h1>Administration USFUR</h1><div class="grid"><form class="box" method="post" action="?route=course_create"><h2>Créer une formation</h2><input name="title" placeholder="Titre" required><textarea name="description" placeholder="Description"></textarea><input type="number" name="module_number" value="1"><input type="number" name="duration_minutes" value="90"><input type="number" name="max_participants" value="50"><select name="status"><option>draft</option><option>published</option><option>live</option><option>completed</option><option>archived</option></select><button class="btn">Créer</button></form><div class="card"><h2>Utilisateurs</h2><p>'.e((string)$pdo->query("SELECT COUNT(*) FROM users")->fetchColumn()).' comptes.</p><p>Les rôles admin/teacher/student sont conservés.</p></div></div>';}
else{http_response_code(404);echo '<h1>Page introuvable</h1>';}foot();